<?php

/**
 * @file
 * Contains global_tag.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_type_alter().
 */
function global_tag_entity_type_alter(array &$entity_types) {
  // This alter will not be needed after a custom_pub will be disabled.
  if (isset($entity_types['custom_publishing_option'])) {
    /* @var \Drupal\Core\Config\Entity\ConfigEntityType $config_entity_type */
    $config_entity_type = &$entity_types['node'];
    $config_entity_type->setHandlerClass('storage', 'Drupal\global_tag\Config\Entity\ConfigEntityStorage');
    drupal_set_message(t('Custom Pub module can be disabled.'), 'warning');
  }
}
