---
#- shell: pwd
#  register: result
#
#- debug:
#    var: result
#    verbosity: 2

#
#- name: Ensure Drupal Console is executable.
#  file:
#    path: "{{ php_env_vars }} {{ drupal_console_path }}"
#    mode: a+x
#    state: file
#
