<?php

/**
 * @file
 * Contains group_following.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function group_following_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the group_following module.
    case 'help.page.group_following':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Group Following') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_entity_base_field_info().
 */
function group_following_entity_base_field_info(EntityTypeInterface $entity_type) {

  if ('group_content' === $entity_type->id()) {
    $fields['group_type_id'] = BaseFieldDefinition::create('string');
    $fields['plugin_id'] = BaseFieldDefinition::create('string');
    return $fields;
  }

}

/**
 * Implements hook_entity_presave().
 */
function group_following_entity_presave(EntityInterface $entity) {

  if ('group_content' === $entity->getEntityTypeId()) {
    /** @var \Drupal\group\Entity\GroupContent $entity */
    $entity->group_type_id->set(0, $entity->getGroup()->getGroupType()->id());
    $entity->plugin_id->set(0, $entity->getContentPlugin()->getPluginId());
  }
}
