<?php

/**
 * @file
 * Contains group_following.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\group\Entity\Group;

/**
 * Implements hook_help().
 */
function group_following_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the group_following module.
    case 'help.page.group_following':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Group Following') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function group_following_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {

  /** @var \Drupal\group_following\GroupFollowingManagerInterface $manager */
  $manager = \Drupal::getContainer()->get('group_following.manager');

  $group_following = $manager->getFollowingByGroup(new Group());

  $result = $group_following->getResultByAccount($account);

  if($result->isFollower() == TRUE) {
    $group_following->follow();
    $group_following->unfollow();
  }


}
