<?php

/**
 * @file
 * Contains group_following.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\group\Entity\Group;

/**
 * Implements hook_help().
 */
function group_following_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the group_following module.
    case 'help.page.group_following':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Group Following') . '</p>';
      return $output;

    default:
  }
}
