# Schema for the configuration files of the Menu Item Visibility By Group Membership module.

menu_item_visibility_by_group.settings:
  type: config_object
  label: 'Automated cron settings'
  mapping:
    mlid:
      type: sequence
      label: 'Plugin ID of menu item'
      sequence:
        type: mapping
        mapping:
          groupe_types:
            type: sequence
            label: 'Visibility group types'
            sequence:
              type: string
              label: 'Group Type name'
