third_party_settings:
  group_following:
    confirmation_popup_following_header: 'Si vous suivez la région,'
    confirmation_popup_following_body: 'vous pourrez  automatiquement suivre tous les pays et les projets de cette région'
    confirmation_popup_unfollowing_header: 'Si vous annulez le lien avec la région,'
    confirmation_popup_unfollowing_body: 'vous continuerez à suivre tous les pays et les projets de cette même région'
