label: Pays
third_party_settings:
  group_following:
    confirmation_popup_following_header: 'Si vous suivez le pays,'
    confirmation_popup_following_body: 'vous pourrez suivre automatiquement tous les projets de ce même pays'
    confirmation_popup_unfollowing_header: 'Si vous annulez le lien avec le pays,'
    confirmation_popup_unfollowing_body: 'le lien avec les projets de ce pays sera automatiquement annulé'
