display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
      fields:
        node_bulk_form:
          label: 'Formulaire des opérations en masse sur les nœuds'
        simplenews_issue:
          label: Bulletin
          separator: ', '
        status:
          label: Published
          separator: ', '
        created:
          label: Updated
        operations:
          label: 'Liens d''actions'
      filters:
        simplenews_issue_target_id_1:
          expose:
            label: Bulletin
  page_1:
    display_title: Page
