display:
  default:
    display_options:
      use_more_text: 'Voir tous les projets'
  block_1:
    display_options:
      use_more_text: 'Voir tous les projets'
  block_full:
    display_options:
      use_more_text: 'Voir tous les projets'
