display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        filename:
          separator: ', '
        filesize:
          separator: ', '
      filters:
        filename:
          expose:
            label: Filename
        filemime:
          expose:
            label: 'File MIME type'
      sorts:
        created:
          expose:
            label: 'Created date'
        filesize:
          expose:
            label: 'File size'
        filename:
          expose:
            label: Filename
