display:
  default:
    display_options:
      header:
        area_text_custom:
          content: 'Filtrer selon:'
      empty:
        area_text_custom:
          content: 'Rien n’a été trouvé'
  product_and_project:
    display_options:
      title: 'Produits & Projets'
    display_title: 'Produits & Projets'
