label: 'Liste des projets'
display:
  default:
    display_options:
      title: Projets
      use_more_text: 'Voir tous les projets'
  block_1:
    display_options:
      use_more_text: 'Voir tous les projets'
  block_2:
    display_title: Région
    display_options:
      use_more_text: 'Voir tous les projets'
  block_3:
    display_options:
      use_more_text: 'Voir tous les pays'
      title: Pays
  block_4:
    display_title: 'Domaine du comité de pilotage'
    display_options:
      use_more_text: 'Voir tous les projets'
  block_full:
    display_options:
      use_more_text: 'Voir tous les projets'
      title: 'Voir tous les projets'
      empty:
        area_text_custom:
          content: 'Rien n''a été trouvé'
  ga_block_full:
    display_options:
      use_more_text: 'Voir tous les projets'
      title: 'Projets du comité de pilotage'
      empty:
        area_text_custom:
          content: 'Rien n''a été trouvé'
  region_full_block:
    display_options:
      use_more_text: 'Voir tous les projets'
      empty:
        area_text_custom:
          content: 'Rien n''a été trouvé'
      title: 'Projets relatives à la region'
