display:
  default:
    display_options:
      empty:
        area:
          content:
            value: "<p>Nothing has been found</p>\r\n"
            format: minimal
  block_frontpage:
    display_options:
      title: 'Nouvelles récentes'
      use_more_text: 'Lire plus d''actualités'
