display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          label: Titre
          separator: ', '
        type:
          label: 'Types de contenu'
          separator: ', '
        status:
          label: Statut
          separator: ', '
        changed:
          label: Actualisé
          separator: ', '
        dropbutton:
          label: 'D''actions'
      filters:
        status:
          expose:
            label: 'Statut publié'
          group_info:
            label: 'Statut publié'
            group_items:
              1:
                title: Publié
                value: '1'
              2:
                title: Unpublished
        type:
          expose:
            label: Type
      empty:
        area_text_custom:
          content: 'No content available.'
      arguments:
        gid:
          exception:
            title: All
      title: Nodes
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Nodes
