label: Content
description: 'Find and manage content.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtre
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        title:
          label: Titre
        type:
          label: 'Types de contenu'
          separator: ', '
        name:
          label: Auteur
        status:
          label: Statut
        changed:
          label: Actualisé
        operations:
          label: 'D''actions'
      filters:
        status:
          expose:
            label: Statut
          group_info:
            label: 'Statut publié'
            group_items:
              1:
                title: Publié
                value: '1'
              2:
                title: Unpublished
        type:
          expose:
            label: 'Types de contenu'
        title:
          expose:
            label: Titre
        langcode:
          expose:
            label: Langue
      title: Content
      empty:
        area_text_custom:
          content: 'No content available.'
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Content
      tab_options:
        title: Content
        description: 'Find and manage content'
    display_title: Page
