display:
  default:
    display_options:
      title: 'Mes projets'
      header:
        area_text_custom:
          content: 'Filtrer selon:'
        custom_to_page:
          title: Edition
      empty:
        area_text_custom:
          content: 'Rien n’a été trouvé'
      filters:
        gid_following:
          expose:
            label: 'Selectionner emplacement'
