display:
  last_comments_by_article:
    display_title: 'Commentaires récents'
    display_options:
      title: 'Derniers commentaires'
  default:
    display_title: Master
    display_options:
      title: 'Commentaires récents'
      empty:
        area_text_custom:
          content: 'No comments available.'
  block_1:
    display_title: Block
    display_options:
      block_description: 'Commentaires récents'
      block_category: 'Lists (Views)'
label: 'Commentaires récents'
description: 'Commentaires récents'
