description: 'Find and manage files.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filtre
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        fid:
          label: Fid
        filename:
          label: Name
        type:
          label: Type
        filesize:
          label: Size
        status:
          label: Statut
        changed:
          label: Changed
          separator: ', '
        count:
          label: 'Used in'
          format_plural_string: "1 place\x03@count places"
        operations:
          label: 'D''actions'
      filters:
        filename:
          expose:
            label: Filename
        status:
          expose:
            label: Statut
        type:
          expose:
            label: Type
      title: Files
      empty:
        area_text_custom:
          content: 'No files available.'
  overview:
    display_title: 'Files overview'
    display_options:
      menu:
        title: Files
  usage:
    display_title: 'File usage'
    display_options:
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        entity_label:
          label: Entity
        type:
          label: 'Entity type'
        module:
          label: 'Registering module'
        count:
          label: 'Use count'
          format_plural_string: "1 place\x03@count places"
      title: 'File usage'
      arguments:
        fid:
          exception:
            title: All
          title: 'File usage information for {{ arguments.fid }}'
