settings:
  default_form_submit_label: Submit
  default_wizard_prev_button_label: '< Previous Page'
  default_wizard_next_button_label: 'Next Page >'
  default_wizard_start_label: Start
  default_preview_next_button_label: Prévisualiser
  default_preview_prev_button_label: '< Previous'
