<?php

/**
 * Implements hook_form_alter().
 */
function document_customization_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_document_form' || $form_id === 'node_document_edit_form') {
    $account = Drupal::currentUser();
    if (!$account->hasPermission('view the administration theme')) {
      // Hide slider paragraphas authenticated users doesn't have access
      // to add paragraphs. They should use the image field only.
      $form['field_document']['#access'] = FALSE;
      // Hide Revision information block.
      $form['revision_information']['#access'] = FALSE;
      // Add custom validate handler to check if Document link or
      // Document file field is filled.
      $form['#validate'][] = 'document_customization_custom_validate';
    }
  }
}

/**
 * Custom validate handler for document create form used by authenticated users.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @return bool
 */
function document_customization_custom_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if($form['#form_id'] === 'node_document_form' || $form['#form_id'] === 'node_document_edit_form') {
    $values = $form_state->getValues();
    if (!empty($values['field_document_link']) && !empty($values['field_document_link'][0]['uri'])) {
      return TRUE;
    }
    elseif (!empty($values['field_document_link']) && !empty($values['field_document_file'][0]['fids'])) {
      return TRUE;
    }
    else {
      $form_state->setError($form, t('Document link or Document file field shouldn\'t be empty.'));
    }
  }
}
