<?php

/**
 * @file
 * Contains group_dashboard.module.
 */
use Drupal\Core\Session\AccountInterface;
use Drupal\group\Entity\Group;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function group_dashboard_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['group_content']->setListBuilderClass('\Drupal\group_dashboard\Controller\GroupRelatedEntitiesListBuilder');
  $entity_types['group']->setListBuilderClass('\Drupal\group_dashboard\Controller\GroupAdminListBuilder');
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function group_dashboard_menu_local_tasks_alter(&$data, $route_name) {
  $user = \Drupal::currentUser();

  switch ($route_name) {
    case 'entity.node.canonical':
      $link_params = $data['tabs'][0][$route_name]['#link']['url']->getRouteParameters();
      $node = Node::load($link_params['node']);

      if (!empty($node) && !$node->access('update', $user)) {
        unset($data['tabs']);
      }
      break;
  }
}

/**
 * Implements hook_views_data_alter().
 */
function group_dashboard_views_data_alter(array &$data) {
  $data['groups_field_data']['gid_admin'] = [
    'real field' => 'gid',
    'filter' => [
      'title' => t('Only admin access'),
      'id' => 'group_admin_filter',
    ],
  ];

  $data['group_content_field_data']['gid_parent_admin'] = [
    'real field' => 'gid',
    'filter' => [
      'title' => t('Parent group admin access'),
      'id' => 'parent_group_filter',
    ],
  ];

  $data['group_content_field_data']['group_select_gid'] = [
    'real field' => 'gid',
    'filter' => [
      'title' => t('Parent group select'),
      'id' => 'group_select_gid',
    ],
  ];

  $data['node_access']['node_operations'] = [
    'title' => t('Access by node operations'),
    'real field' => 'nid',
    'filter' => [
      'id' => 'node_operations_access',
      'help' => t('Filter for content by node access. <strong>Not necessary if you are using node as your base table.</strong>'),
    ],
  ];
}
