<?php

/**
 * Implements hook_form_alter().
 */
function news_customization_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $route = \Drupal::routeMatch()->getRouteName();
  if ($form_id === 'node_news_form') {
    if ($route === 'entity.group_content.create_form') {
      // Hide group's autocomplete.
      $form['field_add_event_in_group']['#access'] = FALSE;
    }

    $current_them = \Drupal::service('theme.manager')->getActiveTheme();
    if ($current_them->getName() === 'ample') {
      // Hide organization field when user is using the ample theme.
      $form['field_organization']['#access'] = FALSE;

      if (!empty($form['field_add_event_in_group']['widget']['#options'])) {
        foreach ($form['field_add_event_in_group']['widget']['#options'] as $key => $values) {
          if ($key !== '_none') {
            // Rename select list group names.
            unset($form['field_add_event_in_group']['widget']['#options'][$key]);

            if (!empty($values)) {
              foreach ($values as $gid => $group_name) {
                // Change the grouping for the options in add in group select list.
                $group = Drupal::entityTypeManager()->getStorage('group')->load($gid);
                if ($group) {
                  $geo_object = array();
                  if ($group->hasField('field_geographical_object')) {
                    $geo_object = $group->get('field_geographical_object')->getValue();
                  }
                  $group_type = $group->getGroupType()->id();
                  if (!empty($geo_object) && isset($geo_object[0]) && $geo_object[0]['value'] === '1') {
                    switch ($group_type) {
                      case 'country':
                        $form['field_add_event_in_group']['widget']['#options']['Country'][$gid] = $group_name;
                        break;
                      case 'region':
                        $form['field_add_event_in_group']['widget']['#options']['Region'][$gid] = $group_name;
                        break;
                      case 'project':
                        $form['field_add_event_in_group']['widget']['#options']['Collaborations'][$gid] = $group_name;
                        break;
                      default:
                        break;
                    }
                  }
                  else {
                    switch ($group_type) {
                      case 'country':
                      case 'country_protected':
                        $manager = \Drupal::service('ggroup.group_hierarchy_manager');
                        $parent_groups = $manager->getGroupSupergroups($group->id());

                        if (!empty($parent_groups)) {
                          $parent_group = $parent_groups[key($parent_groups)];
                          if (isset($parent_group)) {
                            $parent_label = $parent_group->get('label')->getValue();
                            if (!empty($parent_label) && isset($parent_label[0])) {
                              $parent_label = $parent_label[0]['value'];
                              $form['field_add_event_in_group']['widget']['#options']['P4H Areas'][$gid] = $parent_label . ' - ' . $group_name;
                            }
                            else {
                              $form['field_add_event_in_group']['widget']['#options']['P4H Areas'][$gid] = $group_name;
                            }
                          }
                        }
                        break;
                      default:
                        $form['field_add_event_in_group']['widget']['#options']['P4H Areas'][$gid] = $group_name;
                        break;
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

    foreach (array_keys($form['actions']) as $action) {
      if ($action !== 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'news_customization_add_new_news_custom_submit';
      }
    }
  }
  if ($form_id === 'node_news_edit_form') {
    $form['field_add_event_in_group']['#access'] = FALSE;
  }
}

/**
 * Custom submit handler to attach news to group.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function news_customization_add_new_news_custom_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $selected_group = $form_state->getValue('field_add_event_in_group');

  if (!empty($selected_group[0]['target_id'])) {
    // Get the selected group object.
    $selected_gid = $selected_group[0]['target_id'];
    $group = Drupal::entityTypeManager()->getStorage('group')->load($selected_gid);

    /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
    $entity = $form_state->getFormObject()->getEntity();

    // Add the new event to the selected group.
    $group->addContent($entity, 'group_node:news');
  }
}
