<?php

use Drupal\group_following\GroupFollowing;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function news_customization_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $route = \Drupal::routeMatch()->getRouteName();

  if ($form_id === 'node_news_form') {
    if ($route === 'entity.group_content.create_form') {
      // Hide group's autocomplete.
      $form['field_add_event_in_group']['#access'] = FALSE;
    }

    $current_them = \Drupal::service('theme.manager')->getActiveTheme();
    if ($current_them->getName() === 'ample') {
      // Hide organization field when user is using the ample theme.
      $form['field_organization']['#access'] = FALSE;
      $form['field_add_event_in_group']['widget']['#required'] = TRUE;
      $form['field_author']['#access'] = FALSE;

      if (!empty($form['field_add_event_in_group']['widget']['#options'])) {
        $region_options = [];
        $area_options = [];

        foreach ($form['field_add_event_in_group']['widget']['#options'] as $key => $values) {
          if ($key !== '_none') {
            // Rename select list group names.
            if (!is_array($values)) {
              $values = [$key => $values];
            }
            unset($form['field_add_event_in_group']['widget']['#options'][$key]);

            if (!empty($values)) {
              foreach ($values as $gid => $group_name) {
                // Change the grouping for the options in add in group select list.
                $group = Drupal::entityTypeManager()->getStorage('group')->load($gid);

                if ($group) {
                  $geo_object = array();
                  if ($group->hasField('field_geographical_object')) {
                    $geo_object = $group->get('field_geographical_object')->getValue();
                  }
                  $group_type = $group->getGroupType()->id();
                  if (!empty($geo_object) && isset($geo_object[0]) && $geo_object[0]['value'] === '1') {
                    switch ($group_type) {
                      case 'country':
                        $form['field_add_event_in_group']['widget']['#options']['Country'][$gid] = $group_name;
                        break;

                      case 'region':
                        $region_options['Region'][$gid] = $group_name;
                        break;

                      case 'project':
                        $form['field_add_event_in_group']['widget']['#options']['Collaborations'][$gid] = $group_name;
                        break;

                      default:
                        break;
                    }
                  }
                  else {
                    switch ($group_type) {
                      case 'country':
                      case 'country_protected':
                        $manager = \Drupal::service('ggroup.group_hierarchy_manager');
                        $parent_groups = $manager->getGroupSupergroups($group->id());

                        if (!empty($parent_groups)) {
                          $parent_group = $parent_groups[key($parent_groups)];
                          if (isset($parent_group)) {
                            $parent_label = $parent_group->get('label')->getValue();
                            if (!empty($parent_label) && isset($parent_label[0])) {
                              $parent_label = $parent_label[0]['value'];
                              $area_options['P4H Areas'][$gid] = $parent_label . ' - ' . $group_name;
                            }
                            else {
                              $area_options['P4H Areas'][$gid] = $group_name;
                            }
                          }
                        }
                        break;

                      default:
                        $area_options['P4H Areas'][$gid] = $group_name;
                        break;
                    }
                  }
                }
              }
            }
          }
        }

        $empty_option['_none'] = $form['field_add_event_in_group']['widget']['#options']['_none'];
        unset($form['field_add_event_in_group']['widget']['#options']['_none']);
        $clear_options = $form['field_add_event_in_group']['widget']['#options'];

        $form['field_add_event_in_group']['widget']['#options'] = array_merge(
          $empty_option,
          $region_options,
          $area_options,
          $clear_options
        );
      }
    }

    $user_display_name = \Drupal::currentUser()->getDisplayName();
    if (!empty($form['field_author']['widget'])
      && isset($form['field_author']['widget'][0])
      && !empty($form['field_author']['widget'][0]['value'])) {
      // Set current user as author of the node.
      $form['field_author']['widget'][0]['value']['#default_value'] = $user_display_name;
    }

    foreach (array_keys($form['actions']) as $action) {
      if ($action !== 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'news_customization_add_new_news_custom_submit';
      }
    }
  }
  if ($form_id === 'node_news_edit_form') {
    $form['field_add_event_in_group']['#access'] = FALSE;
  }
}

/**
 * Custom submit handler to attach news to group.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function news_customization_add_new_news_custom_submit(&$form, FormStateInterface $form_state) {
  $selected_group = $form_state->getValue('field_add_event_in_group');

  if (!empty($selected_group[0]['target_id'])) {
    // Get the selected group object.
    $selected_gid = $selected_group[0]['target_id'];
    $group = Drupal::entityTypeManager()->getStorage('group')->load($selected_gid);

    /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
    $entity = $form_state->getFormObject()->getEntity();

    // Add the new event to the selected group.
    $group->addContent($entity, 'group_node:news');
  }
}

/**
 * Custom validate handler for news create form used by authenticated users.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @return bool
 */
function news_customization_custom_validate(&$form, FormStateInterface $form_state) {
  if ($form['#form_id'] === 'node_news_form' || $form['#form_id'] === 'node_news_edit_form') {
    $current_theme = \Drupal::service('theme.manager')->getActiveTheme();
    $selected_group = $form_state->getValue('field_add_event_in_group');

    if ($current_theme->getName() === 'ample' && empty($selected_group[0]['target_id'])) {
      $form_state->setError($form, t('P4H Area is required.'));
    }
  }
}
