---
# Commands to prepare environment.
- name: Set writable cache dir
  sudo: yes
  file: path={{ cache_folder }} mode=777 state=directory recurse=yes

- name: Set writable tmp dir
  sudo: yes
  file: dest={{ tmp_folder }} mode=777 state=directory recurse=yes

- name: Set writable backup dir
  sudo: yes
  file: dest={{ backup_folder }} mode=777 state=directory recurse=yes
#workspace}}
- name: Set writable default dir
  sudo: yes
  shell: "{{ php_env_vars }} chmod -R 777 sites/default"
