<?php

/**
 * @file
 * Admin Customizations.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_form_alter().
 */
function admin_customizations_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'file_image_edit_form':
    case 'file_document_edit_form':
      unset($form['uid'], $form['replace_upload']);
      break;

    case 'node_document_form':
    case 'node_document_edit_form':
      foreach (array_keys($form['actions']) as $action) {
        if (
          $action != 'preview' &&
          isset($form['actions'][$action]['#type']) &&
          $form['actions'][$action]['#type'] === 'submit'
        ) {
          $form['actions'][$action]['#submit'][] = 'admin_customizations_document_form_submit';
        }
      }
      break;

  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function admin_customizations_preprocess_page(array &$variables) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();

  if ($is_admin) {
    $variables['#attached']['library'][] = 'ample/admin-page';
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function admin_customizations_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (
    $entity->getEntityTypeId() === 'file' &&
    $entity->getMimeType() === 'image/svg+xml' &&
    isset($build['uri'])
  ) {
    $build['uri'][0]['#theme'] = 'image';
    unset($build['uri'][0]['#image_style']);
  }
}

/**
 * Submit handler.
 *
 * @see admin_customizations_form_alter()
 */
function admin_customizations_document_form_submit(array $form, FormStateInterface $form_state) {
  $build_info = $form_state->getBuildInfo();
  $node = $build_info['callback_object']->getEntity();
  $insert = $node->isNew();
  $link = Link::createFromRoute($node->label(), 'entity.node.edit_form', ['node' => $node->id()]);
  $t_args = [
    '@type' => node_get_type_label($node),
    '%title' => $link->toString(),
  ];

  drupal_get_messages();

  if ($insert) {
    drupal_set_message(t('@type %title has been created.', $t_args));
  }
  else {
    drupal_set_message(t('@type %title has been updated.', $t_args));
  }

  $form_state->setRedirectUrl(Url::fromRoute('system.admin_content'));
}

/**
 * Implements hook_link_alter().
 */
function admin_customizations_link_alter(&$variables) {
  if (isset($variables['url']) && !$variables['url']->isExternal() && $variables['url']->getRouteName() == 'masquerade.unmasquerade') {
    $variables['options']['attributes']['class'][] = 'unmasquerade-link';
  }
}
