<?php

/**
 * @file
 * Notification Customizations.
 */

/**
 * Implements hook_mail_alter().
 */
function notification_customizations_mail_alter(&$message) {
  $message['from'] = \Drupal::config('system.site')->get('mail');
  if ($message['key'] == 'register_pending_approval_admin') {
    $raw_admin_emails = \Drupal::config('notification_customizations.settings')->get('notification_customizations.settings.emails');
    if (!empty($raw_admin_emails)) {
      $array_emails = preg_split('/\r\n?|\n/', $raw_admin_emails);
      $admin_emails = implode(",", $array_emails);
      $message['headers']['Bcc'] = $admin_emails;
    }
  }
}
