field.widget.settings.daterange_eventdaterange:
  type: mapping
  label: 'Date only range display format settings'
  mapping:
    value:
      type: string
      label: 'Date Format'
    format:
      type: string
      labrl: 'Date type'
