field.widget.settings.daterange_time:
  type: mapping
  label: 'Time range display format settings'
  mapping:
    value:
      type: string
      label: 'Date Format'

field.widget.settings.daterange_dateonly:
  type: mapping
  label: 'Date only range display format settings'
  mapping:
    value:
      type: string
      label: 'Date Format'
