<?php

/**
 * @file
 * Group customization module main file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_preprocess_html().
 */
function group_customization_preprocess_html(array &$variables) {
  // Add class to body by group context.
  if (($group = \Drupal::routeMatch()->getParameter('group')) && $group->id()) {
    $variables['attributes']['class'][] = 'group-' . $group->bundle();
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function group_customization_group_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // @var \Drupal\group_customization\Access\GroupPermissionAccessCheck $groupPermissionAccess
  $groupPermissionAccess = \Drupal::getContainer()
    ->get('group_customization.group.permission');
  return $groupPermissionAccess->checkAccess($entity, $operation, $account, [
    'published',
    'content',
  ]);
}
