<?php
/**
 * @file
 * Contains p4h_views_plugins.module.
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function p4h_views_plugins_theme() {
  \Drupal::moduleHandler()
    ->loadInclude('p4h_views_plugins', 'inc', 'p4h_views_plugins.theme');
  return [
    'p4h_views_plugins' => [
      'file' => 'p4h_views_plugins.theme.inc',
      'template' => 'p4h_views_plugins',
      'variables' => [
        'tags' => [],
        'options' => [],
        'quantity' => 9,
        'element' => 0,
        'parameters' => []
      ],
    ],
  ];
}


/**
 * Implements hook_form_alter().
 */
function p4h_views_plugins_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form'
    && $form['#id'] == 'views-exposed-form-news-events-block-1'
  ) {
    $form['wrap'] = [
      '#prefix' => '<div class="wrapper-filters">',
      '#suffix' => '</div>',
      '#weight' => -100,
    ];
    $form['wrap']['year'] = $form['year'];
    $form['wrap']['month'] = $form['month'];
    unset($form['year'], $form['month']);
    $form['#attached']['drupalSettings'] = ['defaultFormSelector' => '#' . $form['#id']];
  }
}

