<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\form_alter_service\Interfaces\FormAlterServiceAlterInterface;

/**
 * Implements hook_form_alter().
 */
function form_alter_service_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $service = Drupal::service('form_alter_service.alter');
  /* @var $service \Drupal\form_alter_service\Service\FormAlterServiceAlter */
  $alters = $service->getFormAlter($form_id) + $service->getFormAlter('match');
  foreach ($alters as $alter) {
    /* @var $alter \Drupal\form_alter_service\Interfaces\FormAlterServiceAlterInterface */
    if ($alter instanceof FormAlterServiceAlterInterface && $alter->hasMatch($form, $form_state, $form_id)) {
      $alter->formAlter($form, $form_state);
      $form['#validate'][] = [$alter, 'formValidate'];
      $form['#validate'][] = [$alter, 'formSubmit'];
    }
  }
}
