<?php

/**
 * @file
 * Contains knowledge_vault.module.
 */

/**
 * Implements hook_views_data_alter().
 */
function knowledge_vault_views_data_alter(array &$data) {
  $data['taxonomy_term_field_data']['tags_by_group'] = [
    'real field' => 'tid',
    'filter' => [
      'title' => t('Tags by group'),
      'id' => 'tags_by_group',
    ],
  ];

  $data['group_content_field_data']['parents_content'] = [
    'argument' => [
      'title' => t('Has parent ID for get parent contents'),
      'id' => 'parents_content',
    ],
  ];
}

