<?php

/**
 * @file
 * Contains knowledge_vault.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\tagadelic\TagadelicTag;
use Drupal\views\ResultRow;

/**
 * Implements hook_form_alter().
 */
function knowledge_vault_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-article-article') {
    $form['#attributes']['data-links-filter'] = $form['#id'];

    foreach (Element::getVisibleChildren($form) as $name) {
      if (isset($form[$name]['#type']) && 'select' === $form[$name]['#type']) {
        $tags = [];
        $options = [];

        if (!empty($form['#tags_styles'][$name])) {
          $tags = _generate_tag_cloude($form['#tags_styles'][$name]);
        }
        //Extract the options from the Views Exposed Filter <select>-list
        $links = $form[$name]['#options'];

        if (!empty($form['#tags_styles'][$name])) {
          unset($links['All']);
        }

        foreach ($links as $tid => $term_name) {
          $classes = ['filter-tab'];

          if (!empty($form['#tags_styles'][$name]) && isset($tags[$tid])) {
            $classes[] = 'level' . $tags[$tid];
          }

          $element = [
            '#type' => 'html_tag',
            '#tag' => 'span',
            '#attributes' => [
              'class' => $classes,
            ],
            '#value' => '<a href="" id="' . $tid . '">' . $term_name . '</a>',
          ];

          if ($tid == 'All') {
            $element = $element + [
              '#value' => '<a href="" class="active" id="' . $tid . '">' . t('All') . '</a>',
            ];
          }

          $options[] = $element;
        }

        $form[$name . '_wrap'] = [
          '#prefix' => '<div class="links-filter-wrapper">',
          '#suffix' => '</div>',
          '#weight' => -100,
        ];

        $form[$name . '_wrap'][$name] = $form[$name];

        unset($form[$name]);

        if (!empty($form['#info']["filter-$name"]['label'])) {
          $form[$name . '_wrap'][$name . '_label'] = [
            '#type' => 'markup',
            '#markup' => $form['#info']["filter-$name"]['label'],
            '#prefix' => '<span class="filter-label">',
            '#suffix' => '</span>',
          ];
        }

        $form[$name . '_wrap'][$name . '_links'] = [
          '#theme' => 'item_list',
          '#items' => $options,
          '#attributes' => ['class' => [str_replace('_', '-', $name)]],
        ];

        $form['title']['#attributes']['placeholder'] = t('Search in articles');

        $form['title']['#prefix'] = '<div class="search-form-wrapper">';
        $form['actions']['#suffix'] = '</div>';
      }
    }

    $form['#attached']['library'][] = 'knowledge_vault/knowledge_vault.enable';
  }
}

/**
 * Implements hook_views_data_alter().
 */
function knowledge_vault_views_data_alter(array &$data) {
  $data['taxonomy_term_field_data']['tags_by_group'] = array(
    'real field' => 'tid',
    'filter' => array(
      'title' => t('Tags by group'),
      'id' => 'tags_by_group',
    ),
  );
}

/**
 * Helper function for generate tag weight.
 *
 * @param array $options
 *   List of tags.
 *
 * @return array
 *  Tags weight.
 */
function _generate_tag_cloude(array $options) {
  $min = 1e9;
  $max = -1e9;
  $steps = 6;
  $tags = [];

  /* @var ResultRow $tag */
  foreach ($options as $tag) {
    $tags[] = new TagadelicTag($tag->_entity->id(), $tag->_entity->label(), $tag->tid);
  }

  /* @var TagadelicTag $tag */
  foreach ($tags as $id => $tag) {
    $min = min($min, $tag->distributed());
    $max = max($max, $tag->distributed());
  }

  // Note: we need to ensure the range is slightly too large to make sure even
  // the largest element is rounded down.
  $range = max(.01, $max - $min) * 1.0001;

  foreach ($tags as $id => $tag) {
    $tags[$tag->getId()] = 1 + floor($steps * ($tag->distributed() - $min) / $range);
    unset($tags[$id]);
  }

  return $tags;
}
