---
env:
  trusted_host_patterns: []
  pre_settings:
    - { name: '$settings["install_profile"]', status: true, value: "{{ installation_profile_name }}" }
    - { name: '$settings["file_public_path"]', status: true, value: 'sites/default/files' }
    - { name: '$config["system.file"]["path.temporary"]', status: true, value: '/tmp' }
  modules:
    - { name: 'devel config_inspector config_devel', status: false }
  drush_commands:
    - { name: 'sqlq', status: true, arguments: "\"UPDATE users_field_data SET name='{{ drupal_user }}' WHERE uid=1\"" }
    - { name: 'upwd', status: true, arguments: "{{ drupal_user }} --password={{ drupal_pass }}" }
    - { name: 'cset', status: true, arguments: "system.site uuid b0409d58-21df-4959-aec9-4b93adf7d064 -y" }
    - { name: 'cim', status: true, arguments: "-y" }
    # Plese do not use drush for importing configs. See https://www.youtube.com/watch?v=vFsgNjhGr4Y for how to use http://dgo.to/confi
    - { name: 'cr', status: true, arguments: "" }
    - { name: 'search-index', status: false, arguments: "" }
  post_settings:
    - { name: '$settings["cache"]["bins"]["render"]', status: false, value: 'cache.backend.memory' }
    - { name: '$config["stage_file_proxy.settings"]["origin"]', status: false, value: '{{ origin_site_url }}' }

