---
env:
  trusted_host_patterns: []
  pre_settings:
    - { name: '$settings["file_public_path"]', status: true, value: 'sites/default/files' }
    - { name: '$config["system.file"]["path.temporary"]', status: true, value: '/tmp' }
  modules:
    - { name: 'devel config_inspector config_devel', status: false }
  drush_commands:
    - { name: 'sqlq', status: true, arguments: "\"UPDATE users_field_data SET name='{{ drupal_user }}' WHERE uid=1\"" }
    - { name: 'upwd', status: true, arguments: "{{ drupal_user }} --password={{ drupal_pass }}" }
    # Plese do not use drush for importing configs.
    # See https://www.youtube.com/watch?v=vFsgNjhGr4Y
    # for how to use http://dgo.to/confi.
    # Update: New meta config_split for local configs
    - { name: 'cr', status: true, arguments: "" }
    - { name: 'search-index', status: false, arguments: "" }
  post_settings:
    - { name: '$config["stage_file_proxy.settings"]["origin"]', status: true, value: '{{ origin_site_url }}' }
    - { name: '$config["stage_file_proxy.settings"]["hotlink"]', status: true, value: '1' }
    - { name: '$settings["cache"]["bins"]["render"]', status: false, value: 'cache.backend.memory' }
