---
env:
  trusted_host_patterns: []
  pre_settings: []
  modules: []
  drush_commands:
    - { name: 'sqlq', status: true, arguments: "\"UPDATE users_field_data SET name='{{ drupal_user }}' WHERE uid=1\"" }
    - { name: 'upwd', status: true, arguments: "{{ drupal_user }} --password={{ drupal_pass }}" }
    - { name: 'search-index', status: false, arguments: "" }
  post_settings: []
