---
global_env:
  # Protecting against HTTP HOST Header attacks (https://www.drupal.org/node/1992030).
  trusted_host_patterns: []
  pre_settings:
    - { name: '$settings["install_profile"]', status: true, value: "{{ installation_profile_name }}" }
    - { name: '$settings["hash_salt"]', status: true, value: '{{ hash_salt }}' }
    - { name: '$config_directories[CONFIG_SYNC_DIRECTORY]', status: true, value: '{{ sync_stage }}' }
    - { name: '$settings["file_private_path"]', status: true, value: 'sites/default/files/private' }
  pre_settings_raw:
    - { name: '$databases["migrate"]["default"]', status: true, value:  '[
                                                                            "database" => "db11149163-p4hintranet",
                                                                            "username" => "{{ mysql_user }}",
                                                                            "password" => "{{ mysql_pass }}",
                                                                            "driver" => "{{ mysql_driver | default("mysql") }}",
                                                                            "prefix" => "{{ mysql_prefix | default }}",
                                                                            "port" => {{ mysql_port | default(3306) }},
                                                                            "host" => "{{ mysql_host }}",
                                                                          ];' }
  modules: []
  drush_commands: []
      #- { name: 'cset', status: true, arguments: "system.site uuid b0409d58-21df-4959-aec9-4b93adf7d064 -y" }
      #- { name: 'cim', status: true, arguments: "-y" }
      # @todo Remove this
      # - { name: 'cr', status: true, arguments: "-y" }
      # - { name: 'cim', status: true, arguments: "-y" }
  post_settings:
    - { name: '$settings["pp_environment"]', status: true, value: "{{ pp_environment }}" }
