buttons_size: 32
additional_html: "<a class=\"a2a_button_email\"></a>\r\n<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_twitter\"></a>\r\n<a class=\"a2a_button_linkedin\"></a>"
additional_css: ''
additional_js: "a2a_config.templates.email = {\r\n    subject: \"${title}\",\r\n    body: \"Hello,\\nI thought you might be interested in this page in the Health Systems Governance Collaborative: ${link}\"\r\n};"
universal_button: none
custom_universal_button: ''
universal_button_placement: before
no_3p: false
_core:
  default_config_hash: 8aJF-FDdnrk-N2gLGWFQcLZIpuJZA0BE9NtgXTVJfVk
