features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: true
favicon:
  use_default: 0
  path: 'public://android-chrome-256x256.png'
  mimetype: image/png
