module:
  admin_customizations: 0
  block: 0
  block_content: 0
  block_page_layout: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  config: 0
  config_devel: 0
  config_import: 0
  config_translation: 0
  contact: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  deployment: 0
  devel: 0
  devel_generate: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  events: 0
  field: 0
  field_formater_render_twice: 0
  field_ui: 0
  file: 0
  file_browser: 0
  file_entity: 0
  filter: 0
  ggroup: 0
  gnode: 0
  grolesync: 0
  group: 0
  help: 0
  history: 0
  image: 0
  image_url_formatter: 0
  language: 0
  layout_plugin: 0
  link: 0
  locale: 0
  members: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  paragraphs: 0
  paragraphs_type_permissions: 0
  path: 0
  prev_next_access: 0
  quickedit: 0
  rdf: 0
  search: 0
  shortcut: 0
  stage_file_proxy: 0
  system: 0
  taxonomy: 0
  text: 0
  timeline: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  update: 0
  user: 0
  video_embed_field: 0
  view_mode_selector: 0
  views_ui: 0
  menu_link_content: 1
  content_translation: 10
  views: 10
  pp: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  ample: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
