module:
  addtoany: 0
  admin_customizations: 0
  admin_theme: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_page_layout: 0
  blocktabs: 0
  breakpoint: 0
  captcha: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  coffee: 0
  color: 0
  comment: 0
  composer_manager: 0
  config: 0
  config_devel: 0
  config_import: 0
  config_translation: 0
  contact: 0
  contextual: 0
  country: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  custom_pub: 0
  custom_validation: 0
  datetime: 0
  datetime_range: 0
  datetime_select: 0
  dblog: 0
  deployment: 0
  devel: 0
  devel_generate: 0
  diff: 0
  disable_messages: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  email_confirm: 0
  email_registration: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  entity_legal: 0
  entity_reference_revisions: 0
  events: 0
  field: 0
  field_formater_render_twice: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  field_validation: 0
  file: 0
  file_browser: 0
  file_entity: 0
  filter: 0
  form_alter_service: 0
  form_mode_manager: 0
  formblock: 0
  geolocation: 0
  gnode: 0
  grolesync: 0
  group: 0
  group_content_field: 0
  group_content_formatters: 0
  group_customization: 0
  group_dashboard: 0
  group_parent_context: 0
  help: 0
  history: 0
  image: 0
  image_url_formatter: 0
  image_widget_crop: 0
  language: 0
  layout_plugin: 0
  link: 0
  linkit: 0
  locale: 0
  mailsystem: 0
  masquerade: 0
  members: 0
  menu_item_visibility: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  migrate: 0
  migrate_api: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_social: 0
  migrate_social_implementation: 0
  migrate_tools: 0
  mimemail: 0
  node: 0
  options: 0
  p4h_svg_formatter: 0
  p4h_views_plugins: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  paragraphs: 0
  paragraphs_type_permissions: 0
  path: 0
  prev_next_access: 0
  quickedit: 0
  rdf: 0
  realname: 0
  recaptcha: 0
  rel_content: 0
  rest: 0
  sdk: 0
  sdk_facebook: 0
  sdk_linkedin: 0
  sdk_twitter: 0
  search: 0
  serialization: 0
  shortcut: 0
  smtp: 0
  social_login: 0
  stage_file_proxy: 0
  system: 0
  taxonomy: 0
  text: 0
  timeline: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  twig_xdebug: 0
  update: 0
  user: 0
  user_invitation: 0
  video_embed_field: 0
  view_mode_selector: 0
  views_default_arguments: 0
  views_geojson: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  ggroup: 10
  user_registration: 10
  views: 10
  pp: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  ample: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: pp
