definitions:
  block__admin_display:
    weight: -83
    menu_name: admin
    parent: system.admin_structure
    enabled: true
    expanded: false
  entity__comment_type__collection:
    weight: -77
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__contact_form__collection:
    weight: -76
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__node_type__collection:
    weight: -79
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  field_ui__display_mode:
    weight: -75
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  field_collection__overview_field_collections:
    weight: -70
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__menu__collection:
    weight: -82
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__page__collection:
    weight: -81
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__paragraphs_type__collection:
    weight: -74
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__taxonomy_vocabulary__collection:
    weight: -80
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__view__collection:
    weight: -78
    parent: system.admin_structure
    menu_name: admin
    enabled: true
    expanded: false
  file_entity__types:
    weight: -73
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  'country_group_links:country_news_and_events':
    weight: -48
    menu_name: country-menu
    parent: ''
    enabled: true
    expanded: false
  'country_group_links:country_contact':
    weight: -46
    menu_name: country-menu
    parent: ''
    expanded: false
    enabled: true
  'country_group_links:country_documents':
    weight: -47
    menu_name: country-menu
    parent: ''
    expanded: false
    enabled: true
  'country_group_links:country_faq':
    weight: -45
    menu_name: country-menu
    parent: ''
    expanded: false
    enabled: true
  'country_group_links:country_projects':
    weight: -49
    menu_name: country-menu
    parent: ''
    expanded: false
    enabled: true
  'current_country:current_country':
    weight: -50
    menu_name: country-menu
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
