disable_messages_enable: '1'
disable_messages_filter_by_page: 0
disable_messages_page_filter_paths: ''
disable_messages_enable_debug: '0'
disable_messages_debug_visible_div: '0'
disable_messages_ignore_patterns: "The crop \".*\" were successfully updated for image \".*\".\r\nThe crop \".*\" was successfully added for image \".*\"."
disable_messages_exclude_users: ''
disable_messages_ignore_case: '1'
disable_messages_ignore_regex:
  - '/^The crop ".*" were successfully updated for image ".*".$/i'
  - '/^The crop ".*" was successfully added for image ".*".$/i'
_core:
  default_config_hash: i8jRi1xdFrnvhl-PF4yccZSKtXcGgJAWYTDmKkOMIPE
