domain: ''
domains_option: 1
domains_list: ''
eu_only: false
exclude_paths: "/admin\r\n/*/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/edit\r\n/node/*/delete\r\n/node/*/translations\r\n/group/*/edit\r\n/group/*/delete\r\n/group/*/subgroups\r\n/group/*/members\r\n/group/*/content\r\n/group/*/translations"
export:
  folder: custom
langcode: en
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: minimal
popup_agree_button_message: Accept
popup_agreed_enabled: false
popup_bg_hex: 0779BF
popup_clicking_confirmation: true
popup_delay: 1
popup_disagree_button_message: 'cookie policy.'
popup_enabled: true
popup_find_more_button_message: 'More info'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Hide
popup_info:
  value: "<p>Our website uses cookies. Find out more about our</p>\r\n"
  format: minimal
popup_link: 'https://cibox07.m2.propeople.com.ua/stage/en/terms-and-conditions'
popup_link_new_window: false
popup_position: false
popup_text_hex: ffffff
popup_width: 100%
_core:
  default_config_hash: kfXrsolOPAF-91bVNi2WkyMavN4TSaqPeL_A466DYwU
