domain: ''
domains_option: 1
domains_list: ''
eu_only: false
exclude_paths: "admin\r\n/*/admin\r\nadmin/*\r\nbatch\r\nnode/add*\r\nnode/*/edit\r\nnode/*/delete"
export:
  folder: custom
langcode: en
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: minimal
popup_agree_button_message: Accept
popup_agreed_enabled: false
popup_bg_hex: 0779BF
popup_clicking_confirmation: false
popup_delay: 1
popup_disagree_button_message: Decline
popup_enabled: true
popup_find_more_button_message: 'More info'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Hide
popup_info:
  value: "<p>We use cookies to better understand your preferences and personalize content and our electronic interactions with you. By closing this banner, clicking \"Accept\" or continuing to browse the website, you consent to these cookies.</p>\r\n"
  format: minimal
popup_link: 'https://www.google.com.ua/'
popup_link_new_window: true
popup_position: false
popup_text_hex: ffffff
popup_width: 100%
_core:
  default_config_hash: kfXrsolOPAF-91bVNi2WkyMavN4TSaqPeL_A466DYwU
