gituuid: a6bea228-74f2-4714-880c-1d1070db200a
langcode: en
status: true
dependencies:
  config:
    - field.storage.group.field_geographical_object
    - group.type.project
id: group.project.field_geographical_object
field_name: field_geographical_object
entity_type: group
bundle: project
label: 'Geographical object'
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
