account: '717053'
visibility_pages: 0
pages: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/edit\r\n/user/*/delete\r\n/user/*/translations*\r\n/group/*/edit\r\n/group/*/delete\r\n/group/*/content\r\n/group/*/members\r\n/group/*/subgroups\r\n/group/*/translations*"
visibility_roles: 0
roles:
  anonymous: anonymous
  authenticated: authenticated
_core:
  default_config_hash: XZVveqrSHdGWzmMdaVO8BNxvb4lTfr5EVnatLOVAxNY
