mlid:
  'menu_link_content:c71df185-2f47-4bca-9f97-aab277e1cd32':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:7a180654-75e3-4659-8f23-ea3547f5caa3':
    roles:
      - authenticated
    access_check: false
