mlid:
  'menu_link_content:ebb5bf55-a5a1-47f3-8a73-813328c8a68c':
    group_types:
      - governance_area
  'menu_link_content:0eb1031e-e139-4534-b939-a71711b0bad9':
    group_types: {  }
  'menu_link_content:1d48a8dd-5e80-4857-b32f-6a1710089259':
    group_types: {  }
  'menu_link_content:6bfdebbe-89e4-436c-a075-9f30ec0f8da6':
    group_types: {  }
  'menu_link_content:40a3bea1-5b71-49d1-8aaf-a7987e4ad1cf':
    group_types: {  }
  'menu_link_content:6f799a11-a3b3-4389-8340-32b769345b93':
    group_types: {  }
  'menu_link_content:91fc4150-13e3-4500-94db-f551c74b85b5':
    group_types: {  }
