mlid:
  'menu_link_content:c71df185-2f47-4bca-9f97-aab277e1cd32':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:7a180654-75e3-4659-8f23-ea3547f5caa3':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:7294c46a-2b35-4cfd-88a9-2d180be079e6':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:91fc4150-13e3-4500-94db-f551c74b85b5':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:47f0369f-d5d7-49c3-a2f5-b26dabbd9c44':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:48caa95f-5b32-4420-9057-687c5a229f8e':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:5837addc-1979-4f68-b52e-ed9a44fec04d':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:0b71effd-84d6-4610-8766-1cf7ce2f268a':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:ebb5bf55-a5a1-47f3-8a73-813328c8a68c':
    roles: {  }
    access_check: false
  'menu_link_content:40a3bea1-5b71-49d1-8aaf-a7987e4ad1cf':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:960fc030-7f01-4a79-a8fd-4658a78139aa':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:23362c90-fb1a-4970-b7df-656b0f2c9366':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:3500c42a-b5c8-4640-b511-a621a3623502':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:6f799a11-a3b3-4389-8340-32b769345b93':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:63801510-3345-4f63-8c0e-bed4b123b44d':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:40c374b7-bc26-46f9-b18d-25e5ee7a145d':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:8742ced4-b0b0-4f5e-a0aa-38fb58f5a097':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:2f5b0a04-e972-451c-bdf8-ad67f6e0c8e6':
    roles: {  }
    access_check: false
  'menu_link_content:27f9cc02-7eac-4f83-bbb6-c878276b955a':
    roles: {  }
    access_check: false
  'menu_link_content:0eb1031e-e139-4534-b939-a71711b0bad9':
    roles: {  }
    access_check: false
  'menu_link_content:1d48a8dd-5e80-4857-b32f-6a1710089259':
    roles: {  }
    access_check: false
  'menu_link_content:6bfdebbe-89e4-436c-a075-9f30ec0f8da6':
    roles: {  }
    access_check: false
  'menu_link_content:b936951d-96a0-4223-bbfa-9a7ee5bf2e80':
    roles: {  }
    access_check: false
  'menu_link_content:e3988281-4009-4728-888b-06ef778ea701':
    roles: {  }
    access_check: false
  'menu_link_content:c04e568a-43b4-4ea2-82e2-f9bc298ee1f8':
    roles: {  }
    access_check: false
  'menu_link_content:81215e11-4181-4eab-9873-5c74fbf02f5a':
    roles: {  }
    access_check: false
  'menu_link_content:347ec4af-de2f-47c6-a96f-471fbf20ad3a':
    roles: {  }
    access_check: false
  'menu_link_content:972b01b9-8d09-478e-9e7d-a0b6dac1b269':
    roles: {  }
    access_check: false
  'menu_link_content:ef8453a7-3182-4e51-8478-6c4f3cbad72b':
    roles: {  }
    access_check: false
  'menu_link_content:7ff44e80-342a-4dac-81dd-669a83d077af':
    roles: {  }
    access_check: false
  'menu_link_content:6019eb6c-d6f4-4985-af91-969128ce6ee2':
    roles: {  }
    access_check: false
  'menu_link_content:4ebb5574-935c-4e87-a0ba-eabb29c08d5c':
    roles: {  }
    access_check: false
  'menu_link_content:0182e981-5107-45ae-ac0e-e16170e7840f':
    roles: {  }
    access_check: false
  'menu_link_content:35819a8b-bf55-41dc-bd2b-fd5c02d2bde7':
    roles: {  }
    access_check: false
  'menu_link_content:0d31edec-89d6-423b-b68a-045264525875':
    roles: {  }
    access_check: false
  'menu_link_content:d443cf10-13d8-4b93-941b-fd4963dfa9e4':
    roles: {  }
    access_check: false
  'menu_link_content:639028a5-64b4-4d64-99f6-5eace11364bd':
    roles: {  }
    access_check: false
  'menu_link_content:703ae3f7-48dd-43ff-92fb-29360df4e860':
    roles: {  }
    access_check: false
  'menu_link_content:1b2e9c82-5a42-4f5f-acdf-dde6ca30688c':
    roles: {  }
    access_check: false
  'menu_link_content:e74ff43f-c30c-4a29-a0db-abf1cc0bf91c':
    roles: {  }
    access_check: false
  'menu_link_content:3bc7625f-1655-48e0-bd90-318d8e2956c9':
    roles: {  }
    access_check: false
  'menu_link_content:0f79cfa9-de0e-4b67-9621-02d21e01fc39':
    roles: {  }
    access_check: false
  'menu_link_content:da763b37-fc06-451a-ae0b-f1ec6535cb81':
    roles: {  }
    access_check: false
