id: default
label: Default
password_reset: 30
langcode: en
policy_constraints:
  -
    id: password_length
    character_length: 8
    character_operation: minimum
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: uppercase
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: lowercase
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: numeric
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: special
roles:
  authenticated: authenticated
