scheme_whitelist:
  - http
  - https
  - files
  - internal
protocol_style: full
local_paths: "http://intranet.p4h-network.net/\r\nhttps://intranet.p4h-network.net/\r\nhttps://cibox07.m2.propeople.com.ua/stage/"
_core:
  default_config_hash: EKYCulG-Y3pcObfUpVbl-D9T5DDX6d4hpQ-BVlSBAmw
