use_ajax: true
_core:
  default_config_hash: 1kY_ibjpKYrLZZWifcrYumCcksc1NQ5dElTWUvaUGfg
enabled_types_bundles:
  comment:
    - common_comments
  node:
    - event
widget_type: thumbs_up
bot_minute_threshold: '0'
bot_hour_threshold: '0'
botscout_key: ''
