site_key: 6LeuEzwUAAAAAHbbLkO4rBJsyxWuw9YuKXo6y51h
secret_key: 6LeuEzwUAAAAANJP-st6_yJxRjCNA31MdGcjxRDG
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: true
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
