site_key: 6LfJDScUAAAAAL2w9UOsMuPiVJPLKMl8Y4QB83gL
secret_key: 6LfJDScUAAAAADx1UqArNardnnG59mWmXoegJObM
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: true
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
