site_key: 6LfHAzwUAAAAAGwrfAYNSDDW4Mr_igNMopXODb3f
secret_key: 6LfHAzwUAAAAAClzno7pK8NoU-UnwblQGbeAucVg
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: true
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
