smtp_on: true
smtp_host: mailcatcher
smtp_hostbackup: mailcatcher
smtp_port: '1025'
smtp_protocol: standard
smtp_username: ''
smtp_password: ''
smtp_from: ''
smtp_fromname: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
