http_handler: curl
http_protocol: https
api_subdomain: testlogindrupal
api_key: 1cdea33b-4006-4fb2-a9b8-2cd04dc2d693
api_secret: eda53cb0-8f94-40ce-97f0-858dde3a8122
login_page_icons: below
login_page_caption: 'Login with:'
registration_page_icons: above
registration_page_caption: 'Instantly register with:'
profile_page_icons: below
profile_page_caption: 'Link your account to a social network'
registration_approval: inherit
registration_retrieve_avatars: enable
registration_method: manual
provider_amazon: '0'
provider_battlenet: '0'
provider_blogger: '0'
provider_disqus: '0'
provider_draugiem: '0'
provider_dribble: '0'
provider_facebook: '1'
provider_foursquare: '0'
provider_github: '0'
provider_google: '0'
provider_instagram: '0'
provider_linkedin: '1'
provider_livejournal: '0'
provider_mailru: '0'
provider_odnoklassniki: '0'
provider_openid: '0'
provider_paypal: '0'
provider_pinterest: '0'
provider_pixelpin: '0'
provider_reddit: '0'
provider_skyrock: '0'
provider_stackexchange: '0'
provider_steam: '0'
provider_storage: '0'
provider_twitch: '0'
provider_twitter: '1'
provider_vimeo: '0'
provider_vkontakte: '0'
provider_windowslive: '0'
provider_wordpress: '0'
provider_yahoo: '0'
provider_youtube: '0'
