tagadelic_vocabularies:
  tags: tags
  article_type: 0
  categories: 0
  countries: 0
  country_icon: 0
  file_category: 0
  infographic_icons: 0
  members_category: 0
  non_member_organisation: 0
  organizations: 0
  person_titles: 0
  regions: 0
  software_application: 0
