<?php

/**
 * @file
 * Contains simplenews_customizations.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simplenews_customizations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simplenews_customizations module.
    case 'help.page.simplenews_customizations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simplenews Customizations') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_tokens_alter().
 */
function simplenews_customizations_tokens_alter(array &$replacements, array $context, BubbleableMetadata $bubbleable_metadata) {

  if ($context['type'] == 'simplenews-subscriber' && isset($replacements['[simplenews-subscriber:unsubscribe-url]'])) {
    $subscriber = $context['data']['simplenews_subscriber'];
    $hash = simplenews_generate_hash($subscriber->getMail(), 'remove');
    $route_parameters = ['snid' => $subscriber->id(), 'timestamp' => REQUEST_TIME];
    $language = $subscriber->getLangcode();

    $url_arguments = ['absolute' => TRUE, 'langcode' => $language];
    $bubbleable_metadata->setCacheMaxAge(0);
    $route_parameters += [
      'action' => 'remove',
      'newsletter_id' => 'default',
      'hash' => $hash,
    ];
    $replacements['[simplenews-subscriber:unsubscribe-url]'] = \Drupal::url('simplenews.newsletter_confirm_subscription', $route_parameters, $url_arguments);
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function simplenews_customizations_form_user_form_alter(&$form, FormStateInterface $form_state) {
  module_load_include('module', 'simplenews');
  $elements = [];
  /** @var \Drupal\Core\Session\AccountInterface $account */
  $account = $form_state->getFormObject()->getEntity();
  $options = $default_value = $hidden = [];
  simplenews_form_user_register_form_alter($elements, $form_state);
  foreach (simplenews_newsletter_get_all() as $newsletter) {
    /** @var \Drupal\simplenews\NewsletterInterface $newsletter */
    $subscribe_new_account = $newsletter->new_account;
    $opt_inout_method = $newsletter->opt_inout;
    if (($subscribe_new_account == 'on' || $subscribe_new_account == 'off') && ($opt_inout_method == 'single' || $opt_inout_method == 'double')) {
      $options[$newsletter->id()] = $newsletter->description;
      /** @var \Drupal\simplenews\SubscriberInterface $subscriber */
      if (($subscriber = simplenews_subscriber_load_by_mail($account->getEmail())) != FALSE && $subscriber->isSubscribed($newsletter->id())) {
        $default_value[] = $newsletter->id();
      }
    }
  }

  for ($i = 1; $i <= 3; $i++) {
    if (isset($form['submit' . $i])) {
      if (isset($elements['simplenews']['subscriptions'])) {
        $form['subscriptions'] = $elements['simplenews']['subscriptions'];
        $form['subscriptions']['#options'] = $options;
        $form['subscriptions']['#default_value'] = $default_value;

      }
      $instance = \Drupal::classResolver()->getInstanceFromDefinition('\Drupal\simplenews_customizations\Form\SimplenewsNodeTabForm');
      $form['submit' . $i]['#submit'][] = [
        $instance,
        'submitUpdate',
      ];
    }
  }
}
