<?php

/**
 * @file
 * Contains user_registration.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function user_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_registration module.
    case 'help.page.user_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User Registration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function user_registration_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Config\Entity\ConfigEntityType[] $entity_types */
  if($entity_types['user']->getFormClass('register') == 'Drupal\user\RegisterForm') {
    $entity_types['user']->setFormClass('register', '\Drupal\user_registration\UserRegistrationRegister');
  }
  if($entity_types['user']->getFormClass('onetime') == 'Drupal\user\ProfileForm') {
    $entity_types['user']->setFormClass('onetime', '\Drupal\user_registration\ProfileOnetimeForm');
  }
}

/**
 * Implements hook_form_alter().
 */
function user_registration_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if($form_id == 'user_login_form') {
    $form['name']['#prefix'] = '<div class="login-wrapper">';
    $form['actions']['#suffix'] = '</div>';
    unset($form['name']['#description']);
    unset($form['pass']['#description']);

    // @TODO Copy/Paste
    $form['user_links'] = array();
    /*if (\Drupal::config('user.settings')->get('register') != USER_REGISTER_ADMINISTRATORS_ONLY) {
      $form['user_links']['request_password'] = [
        '#type' => 'link',
        '#title' => t('Forgot password'),
        '#url' => Url::fromRoute('user.pass', [], [
          'attributes' => [
            'title' => t('Send password reset instructions via email.'),
            'class' => ['request-password-link'],
          ],
        ]),
      ];
      $form['user_links']['create_account'] = [
        '#type' => 'link',
        '#title' => t('Not a member yet? Sign up here'),
        '#url' => Url::fromRoute('page_manager.page_view_sign_up', [], [
          'attributes' => [
            'title' => t('Not a member yet? Sign up here'),
            'class' => ['create-account-link'],
          ],
        ]),
      ];
    }*/
    $form['actions']['submit']['#value'] = t('Submit');
    /*$form['user_links'] = array(
      '#theme' => 'item_list',
      '#items' => $items,
    );*/
    $form['user_links']['#weight'] = 9;
    $form['name']['#attributes']['placeholder'] = t('Please enter your email');
    $form['pass']['#attributes']['placeholder'] = t('Please enter your password');
    $form['actions']['#weight'] = 10;
  }
  if($form_id == 'user_pass') {
    unset($form['name']['#description']);
  }
  if($form_id == 'user_register_form') {
    $form['name']['#prefix'] = '<div class="login-wrapper register-wrapper">';
    $form['actions']['#suffix'] = '</div>';
    $form['actions']['submit']['#value'] = t('Submit');

    /*$elements = \Drupal\Core\Render\Element::children($form);
    $match_elements = preg_grep('/^social_login_social_login_providers_([0-9]+)/i', $elements);
    foreach ($match_elements as $match_element) {
      $form[$match_element]['#prefix'] = '<div id="left">';
      $form[$match_element]['#suffix'] = '</div>';
    }*/
    unset(
      $form['account']['mail']['#title'],
      $form['account']['notify']
    );
    $form['#group_children']['captcha'] = 'group_right';
    //$form['captcha']['#weight'] = 98;
    //$form['field_accept_term_conditions']['#weight'] = 99;
    //$form['field_disclose_your_personal_det']['#weight'] = 100;
    $title = &$form['field_accept_term_conditions']['widget']['value']['#title'];
    $title = t('Accept @link', [
      '@link' => \Drupal::l(t('term & conditions'), new Url('<front>', [], [
        '_target' => 'blank'
      ]))
    ]);
    /*$title = &$form['field_disclose_your_personal_det']['widget']['value']['#title'];
    $title = \Drupal::l($title, new Url('<front>', [], [
      '_target' => 'blank'
    ]));*/
  }
  if($form_id == 'user_onetime_form') {
    $form['actions']['submit']['#value'] = t('Understood, I am ready to start');
    $form['field_country']['widget']['#title'] = t('Select country of interest');
    $form['field_regions']['widget']['#title'] = t('Select regions of interest');
    $form['field_category']['widget']['#title'] = t('Select categories in the Knowledge Vault');
    unset($form['account']['pass']['#description']);
  }
}

/**
 * Implements hook_entity_extra_field_info_alter().
 */
function user_registration_entity_extra_field_info_alter(&$info) {
  $user_form = &$info['user']['user']['form'];
  $user_form['info_block'] = array(
    'label' => t('Info block'),
    'description' => t('Helper text block.'),
    'weight' => -10,
  );
  $user_form['captcha'] = array(
    'label' => t('Captcha block'),
    'description' => t('Helper captcha block.'),
    'weight' => -10,
  );

}

/**
 * Implements hook_element_info_alter().
 */
function user_registration_element_info_alter(array &$types) {
  if (isset($types['password_confirm'])) {
    $types['password_confirm']['#process'][] = 'user_registration_form_process_password_confirm';
  }
}

/**
 * Form element process handler for client-side password validation.
 *
 * This #process handler is automatically invoked for 'password_confirm' form
 * elements to add the JavaScript and string translations for dynamic password
 * validation.
 */
function user_registration_form_process_password_confirm($element) {
  unset($element['#attached']['drupalSettings']['password']);
  return $element;
}

/**
 * Implements hook_theme().
 */
function user_registration_theme() {
  return [
    'good_to_know' => [
      'template' => 'good_to_know',
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_preprocess_input().
 */
function user_registration_preprocess_input(&$variables, $hook) {
  if (isset($variables['element']['#type']) && FALSE !== strpos($variables['element']['#type'], 'pass')) {
    if ('pass[pass1]' == $variables['attributes']['name']) {
      $variables['attributes']['placeholder'] = t('Please enter your password');
    }
    if ('pass[pass2]' == $variables['attributes']['name']) {
      $variables['attributes']['placeholder'] = t('Please retype your password');
    }
  }
}
