# Schema for the configuration files of the Options module.

field.storage_settings.group_content_item:
  type: mapping
  label: 'Group content item settings'
  mapping:
    gid:
      type: string
      label: 'Value'

field.field_settings.group_content_item:
  type: mapping
  label: 'Group content item settings'
