# Schema for the configuration files of the Options module.

field.storage_settings.list_rel_content:
  type: mapping
  label: 'List of selected plugins'
  mapping:
    list_rel_content_target_types:
      type: sequence
      label: 'Target types'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: string
            label: 'Value'

field.field_settings.list_rel_content:
  label: 'List of selected plugins'
  type: mapping
